#!/usr/bin/env python3
# Import the modules
import subprocess
import sys
import random
import yaml


def read_settings():
   # Find out which path this script is in
   path = sys.path[0]
   # Read settings.yml
   with open(f'{path}/settings.yml','r') as settings:
      return list(yaml.safe_load_all(settings))[0]


# Check if the user specified who to insult
# Check the command line aguments
if len(sys.argv) == 1:
   print('usage: insult name [voice]')
   sys.exit('missing name')
name = sys.argv[1].title()


# Run the read_settings function
settings = read_settings()


# Create a list of insults
insults = settings['insults']


# Choose a random insult
random.seed()
insult = random.choice(insults).format(name = name)



# Check if the user specified a voice
if len(sys.argv) == 3:
   # Set the voice if the user specified one
   voice = sys.argv[2]
else:
   # Set the voice to the default if the user didn't specify one
   voice = settings['voice']


subprocess.run(['say', '-v', voice, insult])