#!/usr/bin/env python3
# Import the modules
import subprocess
import sys
import random


# Check if the user specified who to insult
# Check the command line aguments
if len(sys.argv) == 1:
   print('usage: insult name [voice]')
   sys.exit('missing name')
name = sys.argv[1].title()


# Create a list of insults
insults = [
   f"If there is a zobie apocalypse, {name}, you don't have to worry. They only want people with brains.",
   f"{name}, you're so ugly, you scared the crap out of the toilet.",
   f"{name}, you're the reason they have the middle finger.",
   f"{name} has dog poop on there shoe but it blends in because it looks exactly like them.",
   f"Someday {name} will go far. And I really hope they stay there",
   f"Remember that time {name} was saying that thing I didn’t care about? Yeah, that is now",
   f"{name} is so ugly, they have to trick or treat over the phone",
   f"{name}, I’m busy right now, can I ignore you another time?",
   f"{name}'s secrets are always safe with me. I never even listen when they tell me them.",
]


# Choose a random insult
random.seed()
insult = random.choice(insults)



# Check if the user specified a voice
if len(sys.argv) == 3:
   voice = sys.argv[2]

   # Speak the insult if the user specified a voice
   subprocess.run(['say', '-v', voice, insult])

# Speak the insult if the user did not specify a voice
else:
   subprocess.run(['say', insult])